version: '3'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/web:/usr/share/nginx/html

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    networks:
      - netw

  geoserver:
    build:
      context: ./geoserver
      dockerfile: Dockerfile.geoserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - netw

  util-geoserver:
    build:
      context: ./util-geoserver
      dockerfile: Dockerfile.util-geoserver
    networks:
      - netw
    depends_on:
      - geoserver

  util-postgres:
    build:
      context: ./util-postgres
      dockerfile: Dockerfile.util-postgres
    networks:
      - netw
    depends_on:
      - postgres
    volumes:
      - ./util-postgres/data:/data/
    secrets:
      - postgres_db

networks:
  netw:
    driver: bridge

secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt

  # postgres_user:
  #   file: ./secrets/postgres_user.txt
  # postgres_password:
  #   file: ./secrets/postgres_password.txt


