FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY /init/send_request.py /app

# Upgrade pip and install required Python packages
RUN pip install --upgrade pip && pip install requests

# Define the command to run your script
CMD ["python", "send_request.py"]


