# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your Nginx configuration file if you have a custom one
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy your website files to the default Nginx HTML directory
COPY ./web /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80

# Command to run Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]

